export const municipios = [
    { id: 'ACAMBAY', nombre: 'ACAMBAY DE RUIZ CASTAÑEDA' },
    { id: 'ACULCO', nombre: 'ACULCO' },
    { id: 'ATLACOMULCO', nombre: 'ATLACOMULCO' },
    { id: 'CHAPA_DE_MOTA', nombre: 'CHAPA DE MOTA' },
    { id: 'EL_ORO', nombre: 'EL ORO' },
    { id: 'IXTLAHUACA', nombre: 'IXTLAHUACA' },
    { id: 'JILOTEPEC', nombre: 'JILOTEPEC' },
    { id: 'JIQUIPILCO', nombre: 'JIQUIPILCO' },
    { id: 'JOCOTITLAN', nombre: 'JOCOTITLAN' },
    { id: 'MORELOS', nombre: 'MORELOS' },
    { id: 'POLOTITLAN', nombre: 'POLOTITLAN' },
    { id: 'SOYANIQUILPAN', nombre: 'SOYANIQUILPAN DE JUAREZ' },
    { id: 'TEMASCALCINGO', nombre: 'TEMASCALCINGO' },
    { id: 'TIMILPAN', nombre: 'TIMILPAN' },
    { id: 'ALMOLOYA_DE_JUAREZ', nombre: 'ALMOLOYA DE JUAREZ' },
    { id: 'SAN_FELIPE_DEL_PROGRESO', nombre: 'SAN FELIPE DEL PROGRESO' },
    { id: 'SAN_JOSE_DEL_RINCON', nombre: 'SAN JOSE DEL RINCON' },
    { id: 'TEMOAYA', nombre: 'TEMOAYA' },
    { id: 'ZINACANTEPEC', nombre: 'ZINACANTEPEC' },
    { id: 'DONATO_GUERRA', nombre: 'DONATO GUERRA' },
    { id: 'VILLA_DE_ALLENDE', nombre: 'VILLA DE ALLENDE' },
    { id: 'VILLA_VICTORIA', nombre: 'VILLA VICTORIA' },
    { id: 'ALMOLOYA_DE_ALQUISIRAS', nombre: 'ALMOLOYA DE ALQUISIRAS' },
    { id: 'AMANALCO', nombre: 'AMANALCO' },
    { id: 'AMATEPEC', nombre: 'AMATEPEC' },
    { id: 'IXTAPAN_DEL_ORO', nombre: 'IXTAPAN DEL ORO' },
    { id: 'LUVIANOS', nombre: 'LUVIANOS' },
    { id: 'OTZOLOAPAN', nombre: 'OTZOLOAPAN' },
    { id: 'SAN_SIMON_DE_GUERRERO', nombre: 'SAN SIMON DE GUERRERO' },
    { id: 'SANTO_TOMAS', nombre: 'SANTO TOMAS' },
    { id: 'SULTEPEC', nombre: 'SULTEPEC' },
    { id: 'TEJUPILCO', nombre: 'TEJUPILCO' },
    { id: 'TEMASCALTEPEC', nombre: 'TEMASCALTEPEC' },
    { id: 'TEXCALTITLAN', nombre: 'TEXCALTITLAN' },
    { id: 'TLATLAYA', nombre: 'TLATLAYA' },
    { id: 'VALLE_DE_BRAVO', nombre: 'VALLE DE BRAVO' },
    { id: 'ZACAZONAPAN', nombre: 'ZACAZONAPAN' },
    { id: 'ZACUALPAN', nombre: 'ZACUALPAN' },
    { id: 'COATEPEC_HARINAS', nombre: 'COATEPEC HARINAS' },
    { id: 'IXTAPAN_DE_LA_SAL', nombre: 'IXTAPAN DE LA SAL' },
    { id: 'JOQUICINGO', nombre: 'JOQUICINGO' },
    { id: 'MALINALCO', nombre: 'MALINALCO' },
    { id: 'TENANCINGO', nombre: 'TENANCINGO' },
    { id: 'TENANGO_DEL_VALLE', nombre: 'TENANGO DEL VALLE' },
    { id: 'TONATICO', nombre: 'TONATICO' },
    { id: 'VILLA_GUERRERO', nombre: 'VILLA GUERRERO' },
    { id: 'ZUMPAHUACAN', nombre: 'ZUMPAHUACAN' },
    { id: 'RAYON', nombre: 'RAYON' },
    { id: 'OCUILAN', nombre: 'OCUILAN' },
    { id: 'CALIMAYA', nombre: 'CALIMAYA' },
    { id: 'CAPULHUAC', nombre: 'CAPULHUAC' },
    { id: 'CHAPULTEPEC', nombre: 'CHAPULTEPEC' },
    { id: 'LERMA', nombre: 'LERMA' },
    { id: 'METEPEC', nombre: 'METEPEC' },
    { id: 'MEXICALTZINGO', nombre: 'MEXICALTZINGO' },
    { id: 'OCOYOACAC', nombre: 'OCOYOACAC' },
    { id: 'SAN_ANTONIO_LA_ISLA', nombre: 'SAN ANTONIO LA ISLA' },
    { id: 'SAN_MATEO_ATENCO', nombre: 'SAN MATEO ATENCO' },
    { id: 'TEXCALYACAC', nombre: 'TEXCALYACAC' },
    { id: 'TIANGUISTENCO', nombre: 'TIANGUISTENCO' },
    { id: 'XALATLACO', nombre: 'XALATLACO' },
    { id: 'ALMOLOYA_DEL_RIO', nombre: 'ALMOLOYA DEL RIO' },
    { id: 'ATIZAPAN', nombre: 'ATIZAPAN' },
    { id: 'TOLUCA', nombre: 'TOLUCA' },
    { id: 'XONACATLAN', nombre: 'XONACATLAN' },
    { id: 'HUIXQUILUCAN', nombre: 'HUIXQUILUCAN' },
    { id: 'ISIDRO_FABELA', nombre: 'ISIDRO FABELA' },
    { id: 'JILOTZINGO', nombre: 'JILOTZINGO' },
    { id: 'OTZOLOTEPEC', nombre: 'OTZOLOTEPEC' },
    { id: 'NICOLAS_ROMERO', nombre: 'NICOLAS ROMERO' },
    { id: 'ATIZAPAN_DE_ZARAGOZA', nombre: 'ATIZAPAN DE ZARAGOZA' },
    { id: 'NAUCALPAN_DE_JUAREZ', nombre: 'NAUCALPAN DE JUAREZ' },
    { id: 'CUAUTITLAN_IZCALLI', nombre: 'CUAUTITLAN IZCALLI' },
    { id: 'TULTITLAN', nombre: 'TULTITLAN' },
    { id: 'CUAUTITLAN', nombre: 'CUAUTITLAN' },
    { id: 'MELCHOR_OCAMPO', nombre: 'MELCHOR OCAMPO' },
    { id: 'TULTEPEC', nombre: 'TULTEPEC' },
    { id: 'COACALCO_DE_BERRIOZABAL', nombre: 'COACALCO DE BERRIOZABAL' },
    { id: 'APAXCO', nombre: 'APAXCO' },
    { id: 'COYOTEPEC', nombre: 'COYOTEPEC' },
    { id: 'HUEHUETOCA', nombre: 'HUEHUETOCA' },
    { id: 'HUEYPOXTLA', nombre: 'HUEYPOXTLA' },
    { id: 'TEOLOYUCAN', nombre: 'TEOLOYUCAN' },
    { id: 'TEPOTZOTLAN', nombre: 'TEPOTZOTLAN' },
    { id: 'TEQUIXQUIAC', nombre: 'TEQUIXQUIAC' },
    { id: 'ZUMPANGO', nombre: 'ZUMPANGO' },
    { id: 'VILLA_DEL_CARBON', nombre: 'VILLA DEL CARBON' },
    { id: 'JALTENCO', nombre: 'JALTENCO' },
    { id: 'NEXTLALPAN', nombre: 'NEXTLALPAN' },
    { id: 'TEMASCALAPA', nombre: 'TEMASCALAPA' },
    { id: 'TEOTIHUACAN', nombre: 'TEOTIHUACAN' },
    { id: 'TONANITLA', nombre: 'TONANITLA' },
    { id: 'TECAMAC', nombre: 'TECAMAC' },
    { id: 'ECATEPEC_DE_MORELOS', nombre: 'ECATEPEC DE MORELOS' },
    { id: 'TLALNEPANTLA_DE_BAZ', nombre: 'TLALNEPANTLA DE BAZ' },
    { id: 'LA_PAZ', nombre: 'LA PAZ' },
    { id: 'NEZAHUALCOYOTL', nombre: 'NEZAHUALCOYOTL' },
    { id: 'CHICOLOAPAN', nombre: 'CHICOLOAPAN' },
    { id: 'CHIMALHUACAN', nombre: 'CHIMALHUACAN' },
    { id: 'AMECAMECA', nombre: 'AMECAMECA' },
    { id: 'ATLAUTLA', nombre: 'ATLAUTLA' },
    { id: 'AYAPANGO', nombre: 'AYAPANGO' },
    { id: 'COCOTITLAN', nombre: 'COCOTITLAN' },
    { id: 'ECATZINGO', nombre: 'ECATZINGO' },
    { id: 'JUCHITEPEC', nombre: 'JUCHITEPEC' },
    { id: 'OZUMBA', nombre: 'OZUMBA' },
    { id: 'TEMAMATLA', nombre: 'TEMAMATLA' },
    { id: 'TENANGO_DEL_AIRE', nombre: 'TENANGO DEL AIRE' },
    { id: 'TEPETLIXPA', nombre: 'TEPETLIXPA' },
    { id: 'TLALMANALCO', nombre: 'TLALMANALCO' },
    { id: 'IXTAPALUCA', nombre: 'IXTAPALUCA' },
    { id: 'ACOLMAN', nombre: 'ACOLMAN' },
    { id: 'ATENCO', nombre: 'ATENCO' },
    { id: 'CHIAUTLA', nombre: 'CHIAUTLA' },
    { id: 'CHICONCUAC', nombre: 'CHICONCUAC' },
    { id: 'OTUMBA', nombre: 'OTUMBA' },
    { id: 'PAPALOTLA', nombre: 'PAPALOTLA' },
    { id: 'TEPETLAOXTOC', nombre: 'TEPETLAOXTOC' },
    { id: 'TEXCOCO', nombre: 'TEXCOCO' },
    { id: 'TEZOYUCA', nombre: 'TEZOYUCA' },
    { id: 'AXAPUSCO', nombre: 'AXAPUSCO' },
    { id: 'NOPALTEPEC', nombre: 'NOPALTEPEC' },
    { id: 'SAN_MARTIN_DE_LAS_PIRAMIDES', nombre: 'SAN MARTIN DE LAS PIRAMIDES' },
    { id: 'VALLE_DE_CHALCO_SOLIDARIDAD', nombre: 'VALLE DE CHALCO SOLIDARIDAD' },
    { id: 'CHALCO', nombre: 'CHALCO' }
  ];